### ISSUE TITLE
开机启动时应用报错

### ISSUE THREAD

**Issue by ixuzhen** [songquanpeng/personal-assistant#1]
报错信息如下：
```
Traceback (most recent call last):
  File "main.py", line 203, in <module>
  File "main.py", line 53, in __init__
  File "config.py", line 20, in __setitem__
PermissionError: [Errno 13] Permission denied: 'personal-assistant.ini'
```
使用的版本：`v0.2.1`

报错截图：
![image](https://user-images.githubusercontent.com/66211337/197331458-bb9c8604-3ecd-476b-b631-471cbce9b3bd.png)

**Comment by songquanpeng** [comment]
收到，这应该是工作目录的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月22日(星期六) 下午5:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [songquanpeng/personal-assistant] 开机启动时应用报错 (Issue #1)





 
报错信息如下：
 Traceback (most recent call last):   File "main.py", line 203, in <module&gt;   File "main.py", line 53, in __init__   File "config.py", line 20, in __setitem__ PermissionError: [Errno 13] Permission denied: 'personal-assistant.ini'  
使用的版本：v0.2.1
 
报错截图：
